project_id = "oiwwptnqaunsyhpkwbrz"

[functions.analyze-data]
verify_jwt = false

[functions.get-drive-image]
verify_jwt = false

[functions.sync-species]
verify_jwt = true

[functions.auto-images]
verify_jwt = false

[functions.buscar-imagens-especies]
verify_jwt = false

[functions.parse-rap]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.process-raps-folder]
verify_jwt = false

[functions.sync-afastamentos-sheets]
verify_jwt = false

[functions.identify-species]
verify_jwt = false

[functions.refresh-dashboard-views]
verify_jwt = false

[functions.process-os-folder]
verify_jwt = false

[functions.admin-pessoas]
verify_jwt = true

[functions.sync-auth-password]
verify_jwt = false

[functions.consulta-fipe]
verify_jwt = false

[functions.sync-all-users-auth]
verify_jwt = false

[functions.rap-import]
verify_jwt = false

[functions.sync-radio-operador]
verify_jwt = false

[functions.get-calendar-events]
verify_jwt = false
