project_id = "oiwwptnqaunsyhpkwbrz"

[functions.analyze-data]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-drive-image]
verify_jwt = false

[functions.sync-species]
verify_jwt = true

[functions.auto-images]
verify_jwt = false

[functions.buscar-imagens-especies]
verify_jwt = false

[functions.parse-rap]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.process-raps-folder]
verify_jwt = false
